swagger: "2.0" # https://stackoverflow.com/a/59749691/14797322

info:
  title: "JCP"
  description: "A JWK Set client proxy."
  version: "0.0.1"

schemes:
  - "http"
  - "https"

consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /v1/validate:
    post:
      summary: "Validate a JWT."
      description: "Validate a JWT with the given arguments. Keys from any of the configured remote JWK Set resources can be used to parse it."
      operationId: "validate"
      parameters:
        - in: "body"
          name: "body"
          description: "The JWT validation request."
          required: true
          schema:
            $ref: "#/definitions/ValidateRequest"
      responses:
        200:
          description: "The token has been processed. Make sure to check the response body."
          schema:
            $ref: "#/definitions/ValidateResponse"
        default:
          description: "An error occurred."
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "A copy of the HTTP response status code."
      meta:
        $ref: "#/definitions/RequestMetadata"
      msg:
        type: "string"
        description: "A human-readable error message."

  RequestMetadata:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: "A UUID that uniquely identifies the request."
        format: "uuid"

  ValidateArgs:
    type: "object"
    properties:
      aud:
        type: "array"
        description: "A set of JWT aud claim values to check for. If there are no matching values, validation will fail."
        items:
          type: "string"
      iss:
        type: "array"
        description: "A set of JWT iss claim values to check for. If there are no matching values, validation will fail."
        items:
          type: "string"
      sub:
        type: "array"
        description: "A set of JWT sub claim values to check for. If there are no matching values, validation will fail."
        items:
          type: "string"
      token:
        type: "string"
        description: "The JWT to validate."
    required:
      - "token"

  ValidateRequest:
    properties:
      args:
        $ref: "#/definitions/ValidateArgs"
    required:
      - "args"

  ValidateResponse:
    properties:
      meta:
        $ref: "#/definitions/RequestMetadata"
      results:
        $ref: "#/definitions/ValidateResults"

  ValidateResults:
    properties:
      success:
        type: "boolean"
